version: '0.2'
language: en
allowCompoundWords: true
useGitignore: true
gitignoreRoot: '.' # Prevent searching for .gitignore files past root

ignorePaths:
  - '**/*.{png,jpg,jpeg,gif,svg,icns}'
  - '**/*.min.*'

words:
  - eslint
  - opfs
  - sahpool
  - tsbuildinfo
  - tsconfig
  - tseslint
  - typecheck
  - icns
  - indexeddb
  - myapp
  - Hwaci

dictionaries:
  - css
  - html
  - node
  - npm
  - typescript
  - rust
  - rust-common
  - companies
  - misc
