version: "0.2"
language: en
allowCompoundWords: true
useGitignore: true
gitignoreRoot: .
ignorePaths:
  - "**/*.{png,jpg,jpeg,gif,svg,icns}"
  - "**/*.min.*"
words:
  - eslint
  - haroonwaves
  - Hwaci
  - icns
  - indexeddb
  - myapp
  - opfs
  - sahpool
  - tsbuildinfo
  - tsconfig
  - tseslint
  - typecheck
dictionaries:
  - css
  - html
  - node
  - npm
  - typescript
  - rust
  - rust-common
  - companies
  - misc
